### ISSUE TITLE
java.lang.NoSuchFieldException: driver

### ISSUE THREAD

**Issue by hadrianjmnz90** [eliasnogueira/appium-parallel-execution#5]
Thanks for posting this, but i ran into an issue, i get the following error: `java.lang.NoSuchFieldException: driver`
Where do you declare the field 
`  Field field =  clazz.getDeclaredField("driver");`
that is the thing i need to fix, i checked the rest of your code but i cant figure out what changes should i make.
thanks.

**Comment by amelawadallah** [comment]
1- If you are declaring your driver as private or protected you should changed it to public
2-  If driver is declared at BaseTest as in example , the code should be changed to
            Field field = clazz.getField("driver"); because  getDeclaredField("driver"); gets the value if declared in same class and getField("driver") get the value declared in supper class.

Thanks @eliasnogueira  fore posting this solution  it was exactly what am looking for

**Comment by sachin-narute** [comment]
i changed Field driverField  = clazz.getField("driver"); but still i am facing same issue java.lang.NoSuchFieldException: driver. Unaable to understand what is the exact issue.

**Comment by sachin-narute** [comment]
i used field = clazz.getField("driver"); but still getting java.lang.NoSuchFieldException: driver.

Not sure what is issue.

**Comment by amelawadallah** [comment]
> i used field = clazz.getField("driver"); but still getting java.lang.NoSuchFieldException: driver.
> 
> Not sure what is issue.

can you share your code to check?

**Comment by eliasnogueira** [comment]
Hello guys!
Could you try again?
I've removed the reflection due to the recent changes on JDK 11.

**Comment by kishore369** [comment]
bro it worked,thaks alot

**Comment by eliasnogueira** [comment]
@mukesh90hz Can you send the complete log/exception? Also the Java version you are using.
Thanks :-)

**Comment by pradeepkulal** [comment]
java.lang.NoSuchFieldException: driver
	at java.base/java.lang.Class.getField(Class.java:2117)
	at org.pk.Ecommerce.TestComponents.Listeners.onTestFailure(Listeners.java:33)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:96)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:656)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)



i am facing the same issue please help
